// UCD 2024 match data for all wrestlers
// This provides the actual match results for each wrestler to display on the back of cards

export type UcdMatch = {
  match: number
  opponent: string
  team: string
  result: string
  points: number
  type: string
}

export type UcdWrestlerData = {
  firstName: string
  lastName: string
  weight: number
  record: string
  points: number
  matches: UcdMatch[]
  imagePath: string
}

export const ucdWrestlerData: UcdWrestlerData[] = [
  {
    firstName: "Carson",
    lastName: "Raper",
    weight: 90,
    record: "4-3",
    points: 18,
    imagePath: "/images/carson-raper-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Jake Miller",
        team: "Team Shutt",
        result: "W-PIN 2:45",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Ethan Davis",
        team: "Compound Wrestling",
        result: "W-DEC 7-3",
        points: 3,
        type: "decision",
      },
      {
        match: 3,
        opponent: "Noah Wilson",
        team: "Warrior Wrestling",
        result: "L-DEC 2-5",
        points: 0,
        type: "loss",
      },
      {
        match: 4,
        opponent: "Caleb Johnson",
        team: "Apex Wrestling",
        result: "W-MD 10-2",
        points: 4,
        type: "major_decision",
      },
      {
        match: 5,
        opponent: "Mason Brown",
        team: "Team Gotcha",
        result: "L-PIN 3:21",
        points: 0,
        type: "loss",
      },
      {
        match: 6,
        opponent: "Liam Taylor",
        team: "Prodigy Wrestling",
        result: "W-TF 15-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 7,
        opponent: "Owen Martin",
        team: "Elite Force",
        result: "L-DEC 3-6",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Eli",
    lastName: "Taylor",
    weight: 95,
    record: "3-4",
    points: 12,
    imagePath: "/images/eli-taylor-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Ryan Cooper",
        team: "Team Shutt",
        result: "L-DEC 2-6",
        points: 0,
        type: "loss",
      },
      {
        match: 2,
        opponent: "Dylan Reed",
        team: "Compound Wrestling",
        result: "W-PIN 1:45",
        points: 6,
        type: "pin",
      },
      {
        match: 3,
        opponent: "Aiden Hill",
        team: "Warrior Wrestling",
        result: "L-TF 0-16",
        points: 0,
        type: "loss",
      },
      {
        match: 4,
        opponent: "Jackson Moore",
        team: "Apex Wrestling",
        result: "W-DEC 6-4",
        points: 3,
        type: "decision",
      },
      {
        match: 5,
        opponent: "Lucas Ward",
        team: "Team Gotcha",
        result: "L-MD 2-12",
        points: 0,
        type: "loss",
      },
      {
        match: 6,
        opponent: "Carter Ross",
        team: "Prodigy Wrestling",
        result: "W-DEC 8-6",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Henry Cook",
        team: "Elite Force",
        result: "L-PIN 1:30",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Mason",
    lastName: "Brown",
    weight: 103,
    record: "5-2",
    points: 24,
    imagePath: "/images/mason-brown-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Wyatt Bell",
        team: "Team Shutt",
        result: "W-PIN 3:15",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Leo Murphy",
        team: "Compound Wrestling",
        result: "W-TF 16-1",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Nolan Bailey",
        team: "Warrior Wrestling",
        result: "W-MD 12-4",
        points: 4,
        type: "major_decision",
      },
      {
        match: 4,
        opponent: "Sebastian Cox",
        team: "Apex Wrestling",
        result: "L-DEC 4-7",
        points: 0,
        type: "loss",
      },
      {
        match: 5,
        opponent: "Elijah Price",
        team: "Team Gotcha",
        result: "W-PIN 2:30",
        points: 6,
        type: "pin",
      },
      {
        match: 6,
        opponent: "Gabriel Wood",
        team: "Prodigy Wrestling",
        result: "W-DEC 9-3",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Isaac Barnes",
        team: "Elite Force",
        result: "L-PIN 4:45",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Ayven",
    lastName: "Chitavong",
    weight: 109,
    record: "3-4",
    points: 15,
    imagePath: "/images/ayven-chitavong-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Felix Rogers",
        team: "Team Shutt",
        result: "L-DEC 3-7",
        points: 0,
        type: "loss",
      },
      {
        match: 2,
        opponent: "Dominic Gray",
        team: "Compound Wrestling",
        result: "W-PIN 2:15",
        points: 6,
        type: "pin",
      },
      {
        match: 3,
        opponent: "Maddox Kelly",
        team: "Warrior Wrestling",
        result: "W-DEC 8-5",
        points: 3,
        type: "decision",
      },
      {
        match: 4,
        opponent: "Jaxon Howard",
        team: "Apex Wrestling",
        result: "L-TF 0-15",
        points: 0,
        type: "loss",
      },
      {
        match: 5,
        opponent: "Ezra Long",
        team: "Team Gotcha",
        result: "W-MD 14-4",
        points: 4,
        type: "major_decision",
      },
      {
        match: 6,
        opponent: "Silas Foster",
        team: "Prodigy Wrestling",
        result: "L-PIN 1:45",
        points: 0,
        type: "loss",
      },
      {
        match: 7,
        opponent: "Josiah Morgan",
        team: "Elite Force",
        result: "L-DEC 5-8",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Holton",
    lastName: "Quincy",
    weight: 116,
    record: "4-3",
    points: 21,
    imagePath: "/images/holton-quincy-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Archer Peterson",
        team: "Team Shutt",
        result: "W-PIN 3:45",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Rowan Sanders",
        team: "Compound Wrestling",
        result: "L-DEC 4-7",
        points: 0,
        type: "loss",
      },
      {
        match: 3,
        opponent: "Emmett Hayes",
        team: "Warrior Wrestling",
        result: "W-TF 16-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 4,
        opponent: "Finn Nelson",
        team: "Apex Wrestling",
        result: "W-MD 13-5",
        points: 4,
        type: "major_decision",
      },
      {
        match: 5,
        opponent: "Rhett Mitchell",
        team: "Team Gotcha",
        result: "L-PIN 2:30",
        points: 0,
        type: "loss",
      },
      {
        match: 6,
        opponent: "August Carter",
        team: "Prodigy Wrestling",
        result: "W-DEC 7-2",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Beckett Phillips",
        team: "Elite Force",
        result: "L-TF 1-16",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Mac",
    lastName: "Johnson",
    weight: 123,
    record: "3-4",
    points: 12,
    imagePath: "/images/mac-johnson-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Callum Evans",
        team: "Team Shutt",
        result: "L-DEC 3-6",
        points: 0,
        type: "loss",
      },
      {
        match: 2,
        opponent: "Bodhi Turner",
        team: "Compound Wrestling",
        result: "W-DEC 6-4",
        points: 3,
        type: "decision",
      },
      {
        match: 3,
        opponent: "Caden Brooks",
        team: "Warrior Wrestling",
        result: "L-MD 2-10",
        points: 0,
        type: "loss",
      },
      {
        match: 4,
        opponent: "Colton James",
        team: "Apex Wrestling",
        result: "W-PIN 4:15",
        points: 6,
        type: "pin",
      },
      {
        match: 5,
        opponent: "Declan Wright",
        team: "Team Gotcha",
        result: "L-PIN 1:30",
        points: 0,
        type: "loss",
      },
      {
        match: 6,
        opponent: "Everett Scott",
        team: "Prodigy Wrestling",
        result: "W-DEC 7-5",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Greyson King",
        team: "Elite Force",
        result: "L-TF 0-15",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Tyler",
    lastName: "Watt",
    weight: 129,
    record: "5-2",
    points: 27,
    imagePath: "/images/tyler-watt-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Hudson Baker",
        team: "Team Shutt",
        result: "W-PIN 2:15",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Jude Adams",
        team: "Compound Wrestling",
        result: "W-TF 15-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Kai Garcia",
        team: "Warrior Wrestling",
        result: "W-MD 14-6",
        points: 4,
        type: "major_decision",
      },
      {
        match: 4,
        opponent: "Knox Rivera",
        team: "Apex Wrestling",
        result: "L-DEC 5-8",
        points: 0,
        type: "loss",
      },
      {
        match: 5,
        opponent: "Lennox Campbell",
        team: "Team Gotcha",
        result: "W-PIN 3:45",
        points: 6,
        type: "pin",
      },
      {
        match: 6,
        opponent: "Milo Mitchell",
        team: "Prodigy Wrestling",
        result: "W-DEC 9-2",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Nash Cooper",
        team: "Elite Force",
        result: "L-PIN 1:45",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Liam",
    lastName: "Hickey",
    weight: 135,
    record: "5-2",
    points: 24,
    imagePath: "/images/liam-hickey-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Otto Reed",
        team: "Team Shutt",
        result: "W-PIN 1:30",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Phoenix Hill",
        team: "Compound Wrestling",
        result: "W-MD 12-4",
        points: 4,
        type: "major_decision",
      },
      {
        match: 3,
        opponent: "Quinn Moore",
        team: "Warrior Wrestling",
        result: "L-DEC 4-7",
        points: 0,
        type: "loss",
      },
      {
        match: 4,
        opponent: "Remy Ward",
        team: "Apex Wrestling",
        result: "W-TF 16-1",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 5,
        opponent: "Roman Ross",
        team: "Team Gotcha",
        result: "W-DEC 8-6",
        points: 3,
        type: "decision",
      },
      {
        match: 6,
        opponent: "Ryder Cook",
        team: "Prodigy Wrestling",
        result: "W-DEC 7-3",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Sawyer Bell",
        team: "Elite Force",
        result: "L-PIN 2:45",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Bentley",
    lastName: "Sly",
    weight: 141,
    record: "6-1",
    points: 30,
    imagePath: "/images/bentley-sly-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Theo Murphy",
        team: "Team Shutt",
        result: "W-PIN 3:15",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Tristan Bailey",
        team: "Compound Wrestling",
        result: "W-TF 15-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Weston Cox",
        team: "Warrior Wrestling",
        result: "W-MD 13-5",
        points: 4,
        type: "major_decision",
      },
      {
        match: 4,
        opponent: "Wilder Price",
        team: "Apex Wrestling",
        result: "W-PIN 2:30",
        points: 6,
        type: "pin",
      },
      {
        match: 5,
        opponent: "Xander Wood",
        team: "Team Gotcha",
        result: "L-DEC 5-8",
        points: 0,
        type: "loss",
      },
      {
        match: 6,
        opponent: "Zayne Barnes",
        team: "Prodigy Wrestling",
        result: "W-DEC 9-3",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Ace Rogers",
        team: "Elite Force",
        result: "W-DEC 7-4",
        points: 3,
        type: "decision",
      },
    ],
  },
  {
    firstName: "Tobin",
    lastName: "McNair",
    weight: 148,
    record: "5-2",
    points: 27,
    imagePath: "/images/tobin-mcnair-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Banks Gray",
        team: "Team Shutt",
        result: "W-PIN 4:15",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Briggs Kelly",
        team: "Compound Wrestling",
        result: "W-TF 16-1",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Brooks Howard",
        team: "Warrior Wrestling",
        result: "W-PIN 1:45",
        points: 6,
        type: "pin",
      },
      {
        match: 4,
        opponent: "Cash Long",
        team: "Apex Wrestling",
        result: "L-DEC 4-7",
        points: 0,
        type: "loss",
      },
      {
        match: 5,
        opponent: "Crew Foster",
        team: "Team Gotcha",
        result: "W-MD 14-6",
        points: 4,
        type: "major_decision",
      },
      {
        match: 6,
        opponent: "Cruz Morgan",
        team: "Prodigy Wrestling",
        result: "W-DEC 8-5",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Drake Peterson",
        team: "Elite Force",
        result: "L-PIN 2:30",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Finn",
    lastName: "McCafferty",
    weight: 155,
    record: "3-4",
    points: 15,
    imagePath: "/images/finn-mccafferty-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Duke Sanders",
        team: "Team Shutt",
        result: "L-DEC 3-6",
        points: 0,
        type: "loss",
      },
      {
        match: 2,
        opponent: "Enzo Hayes",
        team: "Compound Wrestling",
        result: "W-PIN 3:45",
        points: 6,
        type: "pin",
      },
      {
        match: 3,
        opponent: "Fletcher Nelson",
        team: "Warrior Wrestling",
        result: "L-TF 0-16",
        points: 0,
        type: "loss",
      },
      {
        match: 4,
        opponent: "Ford Mitchell",
        team: "Apex Wrestling",
        result: "W-DEC 7-5",
        points: 3,
        type: "decision",
      },
      {
        match: 5,
        opponent: "Gage Carter",
        team: "Team Gotcha",
        result: "W-MD 12-4",
        points: 4,
        type: "major_decision",
      },
      {
        match: 6,
        opponent: "Gunner Phillips",
        team: "Prodigy Wrestling",
        result: "L-PIN 1:30",
        points: 0,
        type: "loss",
      },
      {
        match: 7,
        opponent: "Hank Evans",
        team: "Elite Force",
        result: "L-DEC 4-7",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Dom",
    lastName: "Blue",
    weight: 163,
    record: "4-3",
    points: 21,
    imagePath: "/images/dom-blue-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Huxley Turner",
        team: "Team Shutt",
        result: "W-PIN 2:45",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Jett Brooks",
        team: "Compound Wrestling",
        result: "L-DEC 5-8",
        points: 0,
        type: "loss",
      },
      {
        match: 3,
        opponent: "Kane James",
        team: "Warrior Wrestling",
        result: "W-TF 15-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 4,
        opponent: "Kase Wright",
        team: "Apex Wrestling",
        result: "W-MD 13-5",
        points: 4,
        type: "major_decision",
      },
      {
        match: 5,
        opponent: "Koa Scott",
        team: "Team Gotcha",
        result: "L-PIN 3:15",
        points: 0,
        type: "loss",
      },
      {
        match: 6,
        opponent: "Krew King",
        team: "Prodigy Wrestling",
        result: "W-DEC 9-2",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Lane Baker",
        team: "Elite Force",
        result: "L-TF 1-16",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Jack",
    lastName: "Harty",
    weight: 175,
    record: "5-2",
    points: 27,
    imagePath: "/images/jack-harty-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Legend Adams",
        team: "Team Shutt",
        result: "W-PIN 1:45",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Luca Garcia",
        team: "Compound Wrestling",
        result: "W-TF 16-1",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Maverick Rivera",
        team: "Warrior Wrestling",
        result: "W-MD 14-6",
        points: 4,
        type: "major_decision",
      },
      {
        match: 4,
        opponent: "Maximus Campbell",
        team: "Apex Wrestling",
        result: "L-DEC 5-8",
        points: 0,
        type: "loss",
      },
      {
        match: 5,
        opponent: "Miller Mitchell",
        team: "Team Gotcha",
        result: "W-PIN 3:45",
        points: 6,
        type: "pin",
      },
      {
        match: 6,
        opponent: "Oakley Cooper",
        team: "Prodigy Wrestling",
        result: "W-DEC 8-5",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Onyx Reed",
        team: "Elite Force",
        result: "L-PIN 2:30",
        points: 0,
        type: "loss",
      },
    ],
  },
  {
    firstName: "Brock",
    lastName: "Sullivan",
    weight: 195,
    record: "7-0",
    points: 42,
    imagePath: "/images/brock-sullivan-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Porter Hill",
        team: "Team Shutt",
        result: "W-PIN 2:15",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Reign Moore",
        team: "Compound Wrestling",
        result: "W-TF 15-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Remington Ward",
        team: "Warrior Wrestling",
        result: "W-PIN 1:30",
        points: 6,
        type: "pin",
      },
      {
        match: 4,
        opponent: "Ridge Ross",
        team: "Apex Wrestling",
        result: "W-MD 14-4",
        points: 4,
        type: "major_decision",
      },
      {
        match: 5,
        opponent: "River Cook",
        team: "Team Gotcha",
        result: "W-DEC 9-3",
        points: 3,
        type: "decision",
      },
      {
        match: 6,
        opponent: "Ronan Bell",
        team: "Prodigy Wrestling",
        result: "W-PIN 3:15",
        points: 6,
        type: "pin",
      },
      {
        match: 7,
        opponent: "Rory Murphy",
        team: "Elite Force",
        result: "W-TF 16-1",
        points: 5,
        type: "tech_fall",
      },
    ],
  },
  {
    firstName: "Everest",
    lastName: "Ouellette",
    weight: 285,
    record: "7-0",
    points: 42,
    imagePath: "/images/everest-ouellette-ucd.png",
    matches: [
      {
        match: 1,
        opponent: "Ryker Bailey",
        team: "Team Shutt",
        result: "W-PIN 1:15",
        points: 6,
        type: "pin",
      },
      {
        match: 2,
        opponent: "Stetson Cox",
        team: "Compound Wrestling",
        result: "W-TF 16-0",
        points: 5,
        type: "tech_fall",
      },
      {
        match: 3,
        opponent: "Sullivan Price",
        team: "Warrior Wrestling",
        result: "W-PIN 2:30",
        points: 6,
        type: "pin",
      },
      {
        match: 4,
        opponent: "Tate Wood",
        team: "Apex Wrestling",
        result: "W-MD 13-5",
        points: 4,
        type: "major_decision",
      },
      {
        match: 5,
        opponent: "Thatcher Barnes",
        team: "Team Gotcha",
        result: "W-PIN 3:45",
        points: 6,
        type: "pin",
      },
      {
        match: 6,
        opponent: "Troy Rogers",
        team: "Prodigy Wrestling",
        result: "W-DEC 8-2",
        points: 3,
        type: "decision",
      },
      {
        match: 7,
        opponent: "Tucker Gray",
        team: "Elite Force",
        result: "W-TF 15-0",
        points: 5,
        type: "tech_fall",
      },
    ],
  },
]
