import type { CommitCardProps } from "@/components/recruiting/commit-card"

// Sample data for development
export const sampleCommits: CommitCardProps[] = [
  {
    id: 1,
    athleteName: "Liam Hickey",
    firstName: "Liam",
    lastName: "Hickey",
    commitPhotoUrl: "/images/liam-hickey-commit-announcement.png",
    collegeName: "University of North Carolina at Chapel Hill",
    collegeLogo: "/images/logos/unc-logo.png",
    collegeColors: {
      primary: "#7BAFD4",
      secondary: "#FFFFFF",
    },
    highSchool: "Cardinal Gibbons High School",
    highSchoolLogo: "/images/logos/cardinal-gibbons-logo.png",
    club: "RAW Wrestling",
    clubLogo: "/images/logos/raw-wrestling-logo.png",
    graduationYear: 2025,
    weightClass: "133",
    division: "NCAA Division I",
    instagramHandle: "@liam_hickey_wrestling",
    achievements: ["4th Patriot Open", "2x NHSCA All American", "2x State Champ", "4x State Placer", "State Duals MVP"],
    commitmentDate: "2024-08-15",
  },
  {
    id: 2,
    athleteName: "Everest Ouellette",
    firstName: "Everest",
    lastName: "Ouellette",
    commitPhotoUrl: "/images/everest-ouellette-ucd.png",
    collegeName: "Virginia Tech",
    collegeLogo: "/images/logos/vt-logo.png",
    highSchool: "Millbrook High School",
    highSchoolLogo: "/images/logos/millbrook-logo.png",
    club: "NC United Blue",
    clubLogo: "/images/nc-united-logo.png",
    graduationYear: 2025,
    weightClass: "165",
    division: "NCAA Division I",
    instagramHandle: "@everest_wrestling",
    achievements: [
      "State Champion",
      "NHSCA All-American",
      "UWW Cadet World Team",
      "Fargo All-American",
      "Who's #1 Participant",
    ],
    commitmentDate: "2024-10-20",
  },
  {
    id: 3,
    athleteName: "Brock Sullivan",
    firstName: "Brock",
    lastName: "Sullivan",
    commitPhotoUrl: "/images/brock-sullivan-ucd.png",
    collegeName: "UNC Chapel Hill",
    collegeLogo: "/images/logos/unc-logo.png",
    highSchool: "Green Hope High School",
    highSchoolLogo: "/images/logos/green-hope-logo.png",
    club: "NC United Blue",
    clubLogo: "/images/nc-united-logo.png",
    graduationYear: 2025,
    weightClass: "175",
    division: "NCAA Division I",
    instagramHandle: "@brocksullivan_wrestling",
    achievements: ["2x State Finalist", "NHSCA All-American", "Super 32 Placer", "Fargo All-American"],
    commitmentDate: "2024-09-12",
  },
  {
    id: 4,
    athleteName: "Sammy Gantt",
    firstName: "Sammy",
    lastName: "Gantt",
    commitPhotoUrl: "/images/sammy-gantt-nhsca-2025.png",
    collegeName: "Appalachian State",
    collegeLogo: "/images/logos/app-state-logo.png",
    highSchool: "Holly Springs High School",
    highSchoolLogo: "/images/logos/holly-springs-logo.png",
    club: "NC United Gold",
    clubLogo: "/images/nc-united-logo.png",
    graduationYear: 2026,
    weightClass: "150",
    division: "NCAA Division I",
    instagramHandle: "@sammy_gantt",
    achievements: ["State Runner-Up", "NHSCA All-American", "Regional Champion", "Conference Champion"],
    commitmentDate: "2024-10-05",
  },
]
