-- Add all missing columns that the form expects
ALTER TABLE athletes 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS gpa DECIMAL(3,2),
ADD COLUMN IF NOT EXISTS sat_score INTEGER,
ADD COLUMN IF NOT EXISTS act_score INTEGER,
ADD COLUMN IF NOT EXISTS academic_honors TEXT,
ADD COLUMN IF NOT EXISTS image_url TEXT,
ADD COLUMN IF NOT EXISTS commitment_photo_url TEXT,
ADD COLUMN IF NOT EXISTS highlight_video_url TEXT,
ADD COLUMN IF NOT EXISTS intended_major TEXT,
ADD COLUMN IF NOT EXISTS college_commitment TEXT,
ADD COLUMN IF NOT EXISTS division TEXT,
ADD COLUMN IF NOT EXISTS blue_team BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS gold_team BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS red_team BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS black_team BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS white_team BOOLEAN DEFAULT FALSE;
